name: Publish to Github Packages

on:
  push:
    branches:
      - main

run-name: ${{github.workflow}}
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: bun install -g npm
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
